### ISSUE TITLE
Ubuntu version of vagrant machine

### ISSUE THREAD

**Issue by fain182** [filippo-liverani/peperone#6]
I updated the version of ubuntu from 10.04 because it seemed to me too old, but then I checked and saw that the heroku cedar stack is still using ubuntu 10.04, but there is the new cedar-14 that can hosts ubuntu 14.04.

Mays is better if we migrate to it? Or we rollback to ubuntu lucid?

**Comment by filippo-liverani** [comment]
Box updated
